version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER={$DB_USER}
      - POSTGRES_PASSWORD={$DB_PWD}
  web:
    build: .
    command: bash -c "chmod +x emtennis.sh; 
     ./emtennis.sh;
     python emtennis/manage.py migrate;
     python emtennis/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

