# Generated by Django 2.2.3 on 2019-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
