# Generated by Django 2.2.3 on 2019-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190807_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
