# Generated by Django 2.2.3 on 2019-08-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='amount_paid',
            new_name='amount',
        ),
    ]
