# Generated by Django 2.2.3 on 2019-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190812_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='order_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
