# Generated by Django 2.2.3 on 2019-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registration_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
